### ISSUE TITLE
AT-commands via modem manager

### ISSUE THREAD

**Issue by hardd2007** [koshev-msk/luci-app-modeminfo#18]
Приветствую.
В виду того, что в пакете для фиксации используется modem manager, предлагаю функционал по отображению информации о сотах и модеме реализовать через него. Т.к. он постоянно занимает АТ - порты и отображение информации не работает. В новой ветке уже можно компилировать MM с поддержкой АТ команд без обязательного включения debug.

**Comment by koshev-msk** [comment]
- Спасибо за отзыв. Ваше предложение интересно. Однако ввиду того, что модемы могут работать не только в тех режимах, которые поддерживает modemmanager, но и в NCM, ECM, RNDIS, такой переход не будет охватывать все режимы и потребует обязательного наличия modemmanager чего я стараюсь избегать.
- Thanks for the feedback. Your offer is interesting. However, because the modems can work not only in the modes that are supported by ModemManager, but also in the NCM, ECM, RNDIS, this transition will not cover all modes, and will require the obligatory presence of ModemManager, which I try to avoid.

**Comment by koshev-msk** [comment]
In experimental mode will possibe use modeminfo-qmi script for QMI modems via qmicli utility with LTE network mode.

1. Update latest git
2. In `/usr/bin/modeminfo` change path `/usr/share/modeminfo/scripts/modeminfo` to `/usr/share/modeminfo/scripts/modeminfo-qmi`
3. In `/etc/config/modeminfo` change your /dev/cdc-wdm* device

**Comment by koshev-msk** [comment]
Added request via qmicli in experimental mode https://github.com/koshev-msk/luci-app-modeminfo/commit/723101b0ea436376f3b8f87d2bc64eb9c243dc4d
Update latest git.
